services:
    Google_Client:
        class: Google_Client
        calls:
            - [setDeveloperKey, ['%env(GOOGLE_API_KEY)%']]
            - [setClientId, ['%env(GOOGLE_CLIENT_ID)%']]
            - [setClientSecret, ['%env(GOOGLE_CLIENT_SECRET)%']]
            - [setIncludeGrantedScopes, [true]]
            - [setAccessType, ['offline']]
    Google_Service_Drive:
        class: Google_Service_Drive
        autowire: true