hwi_oauth:
    connect:
        account_connector: app.user_provider
    firewall_names: [main]
    fosub:
        username_iterations: 30
        properties:
            google: googleId
    resource_owners:
        google:
            type: google
            client_id: '%env(GOOGLE_ID)%'
            client_secret: '%env(GOOGLE_SECRET)%'
            scope: "email profile"
            options:
                display: popup
                csrf: true
                access_type: offline
                prompt: consent