parameters:
    env(DATABASE_URL): ''

doctrine:
    dbal:
        url: 'sqlite:///%env(resolve:DATABASE_URL)%'
    orm:
        metadata_cache_driver: apcu
        result_cache_driver: apcu
        query_cache_driver: apcu